### ISSUE TITLE
Invalid params: missing field `gasPerPubdata

### ISSUE THREAD

**Issue by liuywme** [zksync-sdk/zksync2-java#11]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/26103265/229455382-cbfd1898-4888-4dab-b9e6-d60120e37779.png">

        <dependency>
            <groupId>io.zksync</groupId>
            <artifactId>zksync2</artifactId>
            <version>0.0.2</version>
        </dependency>

**Comment by liuywme** [comment]
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "Invalid params: missing field `gasPerPubdata`."
    },
    "id": 1
}

**Comment by petarTxFusion** [comment]
This should be resolved with latest release. You can refer to examples here: https://github.com/zksync-sdk/zksync2-examples/tree/main/java
