### ISSUE TITLE
Interacting with smart contracts via Web3j generic Contract 

### ISSUE THREAD

**Issue by tensor0x01** [zksync-sdk/zksync2-java#14]
<img width="1710" alt="image" src="https://user-images.githubusercontent.com/37616560/234756866-f0d6060d-c483-439a-aa07-83ea52346814.png">

**Comment by TakeAwayAntun** [comment]
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/37616560/234775197-54030688-cbc6-4db2-84c7-4631ff9e63b3.png">

**Comment by TakeAwayAntun** [comment]
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/37616560/234775505-9e332abd-5b6a-4546-8626-a1eda9541a9d.png">

**Comment by TakeAwayAntun** [comment]
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/37616560/234775605-a946e548-07e1-4288-aec8-82d116898288.png">

**Comment by TakeAwayAntun** [comment]
The last three pictures, is the way I through the  ZkSyncWallet to call the contract, encountered the problem

**Comment by jiaonliao** [comment]
> 最后三张图，是我通过ZkSyncWallet调使用约的方式，遇到的问题

您解决了嘛，我也遇到了这个问题

**Comment by jiaonliao** [comment]
> 最后三张图，是我通过ZkSyncWallet调用合约的方式，遇到的问题

请问问题解决了吗，我也遇到了这个问题，想请教一下

**Comment by tensor0x01** [comment]
直接放弃使用了

**Comment by tensor0x01** [comment]
> > 最后三张图，是我通过ZkSyncWallet调用合约的方式，遇到的问题
> 
> 请问问题解决了吗，我也遇到了这个问题，想请教一下

直接放弃使用zksync了

**Comment by petarTxFusion** [comment]
This should be resolved with latest release
